/// <reference types="vite/client" />

import {CaseData} from './types';

const caseJsonFiles = import.meta.glob('./static/*.json');

/*
    function to clean path name depending on vite version
    return: string with ./ removed if present
*/
function cleanPathName(p: string): string {
    return p.startsWith('./') ? p.slice(2) : p;
}

//stores all case data in dictionary 
//key is name of path, value is CaseData (see types.ts)
const caseData : Record<string, CaseData> = {};
for(const [path, loader] of Object.entries(caseJsonFiles)){
    //loader represent import statement generated by above glob call
    caseData[cleanPathName(path)] = await loader();
}
/*
    Function to return json data given case path name
    Returns null if case not found
*/
export function getCaseDataByName(caseName: string) : CaseData | null {
    return caseData[caseName] || null;
}

/*
    Function to return caseData object
*/
export function getCaseData() : Record<string, CaseData> {
    return caseData;
}